#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /api/login_check

logout:
  type: rest
  resource: App\Controller\LogoutController
  prefix: api

gesdinet_jwt_refresh_token:
  path: /api/token/refresh
  controller: gesdinet_jwtrefreshtoken::refresh

lists:
  type: rest
  resource: App\Controller\ListController
  prefix: api

tasks:
  type: rest
  resource: App\Controller\TaskController
  prefix: api

notes:
  type: rest
  resource: App\Controller\NoteController
  prefix: api

preferences:
  type: rest
  resource: App\Controller\PreferenceController
  prefix: api
